
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private class Result {
        boolean correct;
        float result;
        
    }
    private void updateResult() {
        ScriptEngineManager Manager = new ScriptEngineManager();
        ScriptEngine Engine = Manager.getEngineByName("JavaScript");
        String Texto = jTextScreen.getText();
        try{
            jTextResult.setText(Engine.eval(Texto).toString());
        } catch (Exception e) {
            jTextResult.setText("");
        }
        jTextResult.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        this.repaint();
    }
    
    private void equals() {
        /*Result result = operate();
        if (result.correct){
            jTextScreen.setText(result.result);
        }
        else{
            jTextScreen.setText("Syntax Error");
        }
        */
    }
    
    private void operate() {
        ScriptEngineManager Manager = new ScriptEngineManager();
        ScriptEngine Engine = Manager.getEngineByName("JavaScript");
        String Texto = jTextScreen.getText();
        try{
            jTextScreen.setText(Engine.eval(Texto).toString());
            jTextResult.setText("");
            jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        } catch (Exception e) {
            jTextResult.setText("Bad expresion");
            jTextResult.setForeground(new java.awt.Color(204, 0, 0));
            jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        }
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextScreen = new javax.swing.JTextField();
        jTextResult = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonReturn = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonMul = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButtonSum = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonComma = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonLPar = new javax.swing.JButton();
        jButtonRPar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora URJC 2016");
        setPreferredSize(new java.awt.Dimension(420, 610));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTextScreen.setEditable(false);
        jTextScreen.setBackground(new java.awt.Color(255, 255, 255));
        jTextScreen.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextScreen.setForeground(new java.awt.Color(51, 51, 51));
        jTextScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextScreen.setToolTipText("");
        jTextScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextScreenActionPerformed(evt);
            }
        });

        jTextResult.setEditable(false);
        jTextResult.setBackground(new java.awt.Color(255, 255, 255));
        jTextResult.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextResult.setForeground(new java.awt.Color(102, 102, 102));
        jTextResult.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextResult.setToolTipText("");
        jTextResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResultActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jButtonReturn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonReturn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReturn.setText("←");
        jButtonReturn.setBorder(null);
        jButtonReturn.setBorderPainted(false);
        jButtonReturn.setContentAreaFilled(false);
        jButtonReturn.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonReturn.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonReturn.setName(""); // NOI18N
        jButtonReturn.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonDiv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiv.setText("÷");
        jButtonDiv.setBorder(null);
        jButtonDiv.setBorderPainted(false);
        jButtonDiv.setContentAreaFilled(false);
        jButtonDiv.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonDiv.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonDiv.setName(""); // NOI18N
        jButtonDiv.setOpaque(false);
        jButtonDiv.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonMul.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonMul.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMul.setText("×");
        jButtonMul.setBorder(null);
        jButtonMul.setBorderPainted(false);
        jButtonMul.setContentAreaFilled(false);
        jButtonMul.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonMul.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonMul.setName(""); // NOI18N
        jButtonMul.setOpaque(false);
        jButtonMul.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulActionPerformed(evt);
            }
        });

        jButtonSub.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSub.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSub.setText("-");
        jButtonSub.setBorder(null);
        jButtonSub.setBorderPainted(false);
        jButtonSub.setContentAreaFilled(false);
        jButtonSub.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonSub.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonSub.setName(""); // NOI18N
        jButtonSub.setOpaque(false);
        jButtonSub.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        jButtonSum.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSum.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSum.setText("+");
        jButtonSum.setBorder(null);
        jButtonSum.setBorderPainted(false);
        jButtonSum.setContentAreaFilled(false);
        jButtonSum.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonSum.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonSum.setName(""); // NOI18N
        jButtonSum.setOpaque(false);
        jButtonSum.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumActionPerformed(evt);
            }
        });

        jButtonEq.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonEq.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEq.setText("=");
        jButtonEq.setBorder(null);
        jButtonEq.setBorderPainted(false);
        jButtonEq.setContentAreaFilled(false);
        jButtonEq.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonEq.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonEq.setName(""); // NOI18N
        jButtonEq.setOpaque(false);
        jButtonEq.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jButtonC.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonC.setText("C");
        jButtonC.setBorder(null);
        jButtonC.setBorderPainted(false);
        jButtonC.setContentAreaFilled(false);
        jButtonC.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonC.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonC.setName(""); // NOI18N
        jButtonC.setOpaque(false);
        jButtonC.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonSeven.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSeven.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeven.setText("7");
        jButtonSeven.setBorder(null);
        jButtonSeven.setBorderPainted(false);
        jButtonSeven.setContentAreaFilled(false);
        jButtonSeven.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonSeven.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonSeven.setName(""); // NOI18N
        jButtonSeven.setOpaque(false);
        jButtonSeven.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSevenActionPerformed(evt);
            }
        });

        jButtonEight.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonEight.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEight.setText("8");
        jButtonEight.setBorder(null);
        jButtonEight.setBorderPainted(false);
        jButtonEight.setContentAreaFilled(false);
        jButtonEight.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonEight.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonEight.setName(""); // NOI18N
        jButtonEight.setOpaque(false);
        jButtonEight.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEightActionPerformed(evt);
            }
        });

        jButtonNine.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonNine.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNine.setText("9");
        jButtonNine.setBorder(null);
        jButtonNine.setBorderPainted(false);
        jButtonNine.setContentAreaFilled(false);
        jButtonNine.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonNine.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonNine.setName(""); // NOI18N
        jButtonNine.setOpaque(false);
        jButtonNine.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });

        jButtonFour.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonFour.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFour.setText("4");
        jButtonFour.setBorder(null);
        jButtonFour.setBorderPainted(false);
        jButtonFour.setContentAreaFilled(false);
        jButtonFour.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonFour.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonFour.setName(""); // NOI18N
        jButtonFour.setOpaque(false);
        jButtonFour.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourActionPerformed(evt);
            }
        });

        jButtonFive.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonFive.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFive.setText("5");
        jButtonFive.setBorder(null);
        jButtonFive.setBorderPainted(false);
        jButtonFive.setContentAreaFilled(false);
        jButtonFive.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonFive.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonFive.setName(""); // NOI18N
        jButtonFive.setOpaque(false);
        jButtonFive.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveActionPerformed(evt);
            }
        });

        jButtonSix.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSix.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSix.setText("6");
        jButtonSix.setBorder(null);
        jButtonSix.setBorderPainted(false);
        jButtonSix.setContentAreaFilled(false);
        jButtonSix.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonSix.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonSix.setName(""); // NOI18N
        jButtonSix.setOpaque(false);
        jButtonSix.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixActionPerformed(evt);
            }
        });

        jButtonOne.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonOne.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOne.setText("1");
        jButtonOne.setBorder(null);
        jButtonOne.setBorderPainted(false);
        jButtonOne.setContentAreaFilled(false);
        jButtonOne.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonOne.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonOne.setName(""); // NOI18N
        jButtonOne.setOpaque(false);
        jButtonOne.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneActionPerformed(evt);
            }
        });

        jButtonTwo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonTwo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTwo.setText("2");
        jButtonTwo.setBorder(null);
        jButtonTwo.setBorderPainted(false);
        jButtonTwo.setContentAreaFilled(false);
        jButtonTwo.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonTwo.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonTwo.setName(""); // NOI18N
        jButtonTwo.setOpaque(false);
        jButtonTwo.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoActionPerformed(evt);
            }
        });

        jButtonZero.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonZero.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZero.setText("0");
        jButtonZero.setBorder(null);
        jButtonZero.setBorderPainted(false);
        jButtonZero.setContentAreaFilled(false);
        jButtonZero.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonZero.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonZero.setName(""); // NOI18N
        jButtonZero.setOpaque(false);
        jButtonZero.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonComma.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonComma.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComma.setText(".");
        jButtonComma.setBorder(null);
        jButtonComma.setBorderPainted(false);
        jButtonComma.setContentAreaFilled(false);
        jButtonComma.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonComma.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonComma.setName(""); // NOI18N
        jButtonComma.setOpaque(false);
        jButtonComma.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommaActionPerformed(evt);
            }
        });

        jButtonThree.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonThree.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThree.setText("3");
        jButtonThree.setBorder(null);
        jButtonThree.setBorderPainted(false);
        jButtonThree.setContentAreaFilled(false);
        jButtonThree.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonThree.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonThree.setName(""); // NOI18N
        jButtonThree.setOpaque(false);
        jButtonThree.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThreeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/urjc.png"))); // NOI18N

        jButtonLPar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonLPar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLPar.setText("(");
        jButtonLPar.setBorder(null);
        jButtonLPar.setBorderPainted(false);
        jButtonLPar.setContentAreaFilled(false);
        jButtonLPar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonLPar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonLPar.setName(""); // NOI18N
        jButtonLPar.setOpaque(false);
        jButtonLPar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonLPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLParActionPerformed(evt);
            }
        });

        jButtonRPar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonRPar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRPar.setText(")");
        jButtonRPar.setBorder(null);
        jButtonRPar.setBorderPainted(false);
        jButtonRPar.setContentAreaFilled(false);
        jButtonRPar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonRPar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonRPar.setName(""); // NOI18N
        jButtonRPar.setOpaque(false);
        jButtonRPar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonRPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRParActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLPar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRPar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonComma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThree, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRPar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLPar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonComma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextScreen)
                    .addComponent(jTextResult))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jTextScreen.setText("");
        jTextResult.setText("");
        updateResult();
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        if(!jTextScreen.getText().isEmpty())
            jTextScreen.setText(jTextScreen.getText().substring(0, jTextScreen.getText().length()-1));
        updateResult();
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSevenActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"7");
        updateResult();
    }//GEN-LAST:event_jButtonSevenActionPerformed

    private void jButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEightActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"8");
        updateResult();
    }//GEN-LAST:event_jButtonEightActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"9");
        updateResult();
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"4");
        updateResult();
    }//GEN-LAST:event_jButtonFourActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"/");
        updateResult();
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMulActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"*");   
        updateResult();        
    }//GEN-LAST:event_jButtonMulActionPerformed

    private void jButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"5");
        updateResult();
    }//GEN-LAST:event_jButtonFiveActionPerformed

    private void jButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"6");
        updateResult();
    }//GEN-LAST:event_jButtonSixActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"-");
        updateResult();
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"1");
        updateResult();
    }//GEN-LAST:event_jButtonOneActionPerformed

    private void jButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"2");   
        updateResult();       
    }//GEN-LAST:event_jButtonTwoActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"0");
        updateResult();
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommaActionPerformed
        jTextScreen.setText(jTextScreen.getText()+".");
        updateResult();
    }//GEN-LAST:event_jButtonCommaActionPerformed

    private void jButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThreeActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"3");
        updateResult();
    }//GEN-LAST:event_jButtonThreeActionPerformed

    private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"+");        
        updateResult();   
    }//GEN-LAST:event_jButtonSumActionPerformed

    private void jButtonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqActionPerformed
        operate();
    }//GEN-LAST:event_jButtonEqActionPerformed

    private void jTextScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextScreenActionPerformed

    private void jButtonLParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLParActionPerformed
        jTextScreen.setText(jTextScreen.getText()+"(");
        updateResult();
    }//GEN-LAST:event_jButtonLParActionPerformed

    private void jButtonRParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRParActionPerformed
        jTextScreen.setText(jTextScreen.getText()+")");
        updateResult();
    }//GEN-LAST:event_jButtonRParActionPerformed

    private void jTextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonComma;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonLPar;
    private javax.swing.JButton jButtonMul;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonRPar;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextResult;
    private javax.swing.JTextField jTextScreen;
    // End of variables declaration//GEN-END:variables
}
